title: "Your Name"
description: "Research • Teaching • Publications"
url: "https://taehyeongterrykim.github.io"
baseurl: ""   # user site must be empty

# Collections, permalinks, etc. (minimal to start)
markdown: kramdown

# Optional defaults (use the theme's home layout if present)
defaults:
  - scope: { path: "" }
    values: { layout: "home" }
