title: "Taehyeong Kim (Terry Kim)"
description: "A Ph.D. candidate in Applied Linguistics at Northern Arizona University (NAU)"
url: "https://taehyeongterrykim.github.io"
baseurl: ""   

markdown: kramdown

defaults:
  - scope: { path: "" }
    values: { layout: "home" }

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag